export const CHANGE_PRODUCT_DETAIL = "CHANGE_PRODUCT_DETAIL";
export const ADD_TO_CARTS = "ADD_TO_CARTS";
export const CHANGE_CART_QUANTILY = "CHANGE_CART_QUANTILY";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
